### PR TITLE
new feature: scram for tcp dialer is supported

### PR DESCRIPTION
**Pull request by wanghaEMQ**
* Integered mqtt tcp dialer part of sdk with scram
* Move scram.h to internal source folder.
* Add encode/decode for msg of auth.
* Support to parse property in auth msg.

### CODE REVIEW

**Review by xinyi-xs — COMMENTED** [review]
Good job!

**Review by JaylinYu — APPROVED** [review]
need to have a deeper test on compatibility with MQTT-TCP
make it draft first

**Comment by wanghaEMQ** [comment]
> need to have a deeper test on compatibility with MQTT-TCP make it draft first

You could easily disable it by -DNNG_ENABLE_SCRAM=OFF

**Comment by JaylinYu** [comment]
I mean, would it affect normal TCP by enabling SCRAM

**Comment by wanghaEMQ** [comment]
> I mean, would it affect normal TCP by enabling SCRAM

okay. it needs more tests.

**Comment by JaylinYu** [comment]
we need more test before next release

**Comment by JaylinYu** [comment]
And make it available on bridging

**Pull request merged**
