### PR TITLE
support postgresql and timescaledb

### PR DESCRIPTION
**Pull request by huchangqiqi**
规则引擎 添加 postgresql 和 timescaledb 支持。

### CODE REVIEW

**Comment by RanMaoyi** [comment]
https://github.com/nanomq/NanoNNG/actions/runs/10613032307/job/29415988960?pr=1057

**Comment by RanMaoyi** [comment]
BTW nng/src/supplemental/nanolib/conf.c print_rule_engine_conf(conf_rule *rule_eng) need to print postgresql and timescaledb too.

**Comment by huchangqiqi** [comment]
I fix error , but still failed.

**Comment by JaylinYu** [comment]
> I fix error , but still failed.

Nevermind, the rest of errors are not your fault.

**Review by JaylinYu — APPROVED** [review]

**Comment by JaylinYu** [comment]
Thanks for your contribution again.

**Pull request merged**
