### PR TITLE
Exchange server support fuzz search request from consumer(ringbuffer and parquet)

### PR DESCRIPTION
**Pull request by RanMaoyi**

### CODE REVIEW

**Comment by JaylinYu** [comment]
it's consumer not customer

**Comment by RanMaoyi** [comment]
> it's consumer not customer

Sorry

**Comment by RanMaoyi** [comment]
code warning need to fix

**Comment by JaylinYu** [comment]
build failed

**Review by wanghaEMQ — APPROVED** [review]

**Review by JaylinYu — APPROVED** [review]

**Pull request merged**
