### PR TITLE
Cancel prior aio from stream layer 

### PR DESCRIPTION
**Pull request by wanghaEMQ**

### CODE REVIEW

**Comment by wanghaEMQ** [comment]
??? Why

**Comment by JaylinYu** [comment]
I was super busy, Need time to review or continue ur wokr

**Comment by wanghaEMQ** [comment]
Okey fine. Feel free to ...

**Comment by wanghaEMQ** [comment]
The changes in this PR has already been contained at https://github.com/nanomq/NanoNNG/pull/732

**Pull request closed without merging**
