### PR TITLE
Exchange_server new api for clean up ringbus

### PR DESCRIPTION
**Pull request by RanMaoyi**

### CODE REVIEW

**Comment by JaylinYu** [comment]
why does Darwin build failed?

**Comment by RanMaoyi** [comment]
> why does Darwin build failed?

Users/runner/work/NanoNNG/NanoNNG/src/supplemental/nanolib/file.c:182:8: error: implicit declaration of function 'mkdir' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        ret = mkdir(fpath, 0777);

**Comment by JaylinYu** [comment]
> > why does Darwin build failed?
> 
> 
> 
> Users/runner/work/NanoNNG/NanoNNG/src/supplemental/nanolib/file.c:182:8: error: implicit declaration of function 'mkdir' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
> 
>         ret = mkdir(fpath, 0777);

Need rebase

**Review by JaylinYu — APPROVED** [review]

**Review by wanghaEMQ — COMMENTED** [review]
It works!

**Pull request merged**
