### PR TITLE
Refactor configuration of exchange

### PR DESCRIPTION
**Pull request by wanghaEMQ**
* New exchange and ringbus structure and its parser.
* Make it easy to extensible to multiple exchanges or multiple ringbuses.
* Print exchange configuration when NanoMQ is started
* Fix the memory leakage when parsing exchange configuration.

### CODE REVIEW

**Comment by wanghaEMQ** [comment]
Seems break CI of exchange

**Comment by wanghaEMQ** [comment]
> Seems break CI of exchange

Will fix it later

**Comment by JaylinYu** [comment]
@RanMaoyi

**Comment by RanMaoyi** [comment]
CI fixed

**Comment by RanMaoyi** [comment]
> CI fixed

Some conflicts need to be resolved

**Review by wanghaEMQ — COMMENTED** [review]
Good job

**Review by lee-emqx — APPROVED** [review]

**Review by JaylinYu — APPROVED** [review]

**Pull request merged**
