### PR TITLE
MQ: Exchange: Key value of msg is stored in stack space

### PR DESCRIPTION
**Pull request by RanMaoyi**

### CODE REVIEW

**Review by lee-emqx — APPROVED** [review]

**Review by wanghaEMQ — APPROVED** [review]
Cool!!! LGTM

**Comment by wanghaEMQ** [comment]
Please don't merge it until my PR is already. I will merge it later

**Review by OdyWayne — APPROVED** [review]

**Review by wanghaEMQ — APPROVED** [review]

**Comment by OdyWayne** [comment]
`exchange_client_test` has failed, plz check it out.

**Comment by wanghaEMQ** [comment]
@JaylinYu Your commits seems break the unit test of exchange

**Comment by RanMaoyi** [comment]
> `exchange_client_test` has failed, plz check it out.

UT begin aio before sock_send, but aio begin in sock_send, fixed now

**Pull request merged**
